### ISSUE TITLE
Contact Attributes not being set on contacts

### ISSUE THREAD

**Issue by jjwilliams42** [amazon-connect/amazon-connect-chat-interface#134] opened 2023-06-23 15:34 UTC
When initializing a chat, the contact attributes are never saved on the contact when looking at their record in Amazon Connect.

Here is our initialization code:

![image](https://github.com/amazon-connect/amazon-connect-chat-interface/assets/1746015/9a4773ca-fa5a-401e-9aeb-a1740f975bc1)

Here are the contact attributes that get stored in Amazon Connect (all of these came from the flow except customerName which came from chat):

![image](https://github.com/amazon-connect/amazon-connect-chat-interface/assets/1746015/4928ec1b-8b3f-4cb7-871a-9de54592f7fa)

**Comment by xiajohn** [comment] 2023-06-23 18:07
Hi, could you try to steps below and see if the issue is still there?

https://github.com/amazon-connect/amazon-connect-chat-ui-examples/issues/108#issuecomment-1571103916

**Comment by mliao95** [comment] 2023-07-27 22:57
Closing issue.  Feel free to re-open if you are still experiencing any issues

**Closed by mliao95** 2023-07-27 22:57 UTC
Labels: ⌛️ Awaiting Response
