### ISSUE TITLE
AccessDeniedException when clicking End Chat

### ISSUE THREAD

**Issue by jjwilliams42** [amazon-connect/amazon-connect-chat-interface#128] opened 2023-06-21 16:22 UTC
When embedding the chat interface into our website - everything works fine until hitting "End Chat" - at that point the spinner comes up 
 and the console displays the following error:

![image](https://github.com/amazon-connect/amazon-connect-chat-interface/assets/1746015/6ab78ea6-6422-48ea-b497-c013f07b51f8)

And the spinner never goes away.

The POST to the disconnect endpoint works fine:

![image](https://github.com/amazon-connect/amazon-connect-chat-interface/assets/1746015/27747dda-dbdd-4540-b88d-02934ab24897)

But it seems the POST to the participant event endpoint fails:

![image](https://github.com/amazon-connect/amazon-connect-chat-interface/assets/1746015/3dd6a5f5-7934-4ea7-8541-49085d16a6b0)

**Comment by spencerlepine** [comment] 2023-07-06 20:04
Hi @jjwilliams42, thank you for taking the time to raise this issue. This is could be an error with the underlying [ChatJS](https://github.com/amazon-connect/amazon-connect-chatjs) library, but we may need more details to investigate. At this time, the team does not have a solution to resolve your issue.

Can you provide more details about your setup?

- Are you experiencing this issue with the Amazon Connect OOTB widget ([Documentation](https://docs.aws.amazon.com/connect/latest/adminguide/add-chat-to-website.html)), or a custom chat interface UI that you are building?
- Has this impacted any other chat functionality that is block this use case?
- Is this error occurring for every single chat widget rendering on your website?
- Is this preventing the user from starting a new chat even after closing/opening the widget?
- What POST `/participant/event` request is being sent?

I am not sure how to reproduce this, would you be able to include steps to repro this issue as well?

https://github.com/amazon-connect/amazon-connect-chat-interface/assets/60903378/7980fda4-0355-4722-9559-6b206eb77226

https://github.com/amazon-connect/amazon-connect-chat-interface/assets/60903378/420acc6c-fef9-43be-883f-241779b005fa

> Reference: we have public documentation for [common errors](https://docs.aws.amazon.com/en_us/connect/latest/adminguide/ts-cw.html), but this error is not covered there currently

**Comment by mliao95** [comment] 2023-07-27 23:01
Hi @jjwilliams42,

I wanted to check in to see if you are still facing this issue. If you are, we would love to help but would need some more details about your setup.  Thanks!

**Comment by mhiaror** [comment] 2023-08-16 15:45
No response from Customer; Closing issue. 
@jjwilliams42, feel free to re-open with more details if you are still facing this issue.

**Closed by mhiaror** 2023-08-16 15:45 UTC
Labels: ⌛️ Awaiting Response

**Comment by pespinozadi** [comment] 2023-08-23 17:09
> Hi @jjwilliams42, thank you for taking the time to raise this issue. This is could be an error with the underlying [ChatJS](https://github.com/amazon-connect/amazon-connect-chatjs) library, but we may need more details to investigate. At this time, the team does not have a solution to resolve your issue.
> 
> Can you provide more details about your setup?
> 
> * Are you experiencing this issue with the Amazon Connect OOTB widget ([Documentation](https://docs.aws.amazon.com/connect/latest/adminguide/add-chat-to-website.html)), or a custom chat interface UI that you are building?
> * Has this impacted any other chat functionality that is block this use case?
> * Is this error occurring for every single chat widget rendering on your website?
> * Is this preventing the user from starting a new chat even after closing/opening the widget?
> * What POST `/participant/event` request is being sent?
> 
> I am not sure how to reproduce this, would you be able to include steps to repro this issue as well?
> 
>  reprotest.mov 
>  ccp.test.mov 
> > Reference: we have public documentation for [common errors](https://docs.aws.amazon.com/en_us/connect/latest/adminguide/ts-cw.html), but this error is not covered there currently


Hi, I reopen this issue. Have the same problem.

> * Are you experiencing this issue with the Amazon Connect OOTB widget ([Documentation](https://docs.aws.amazon.com/connect/latest/adminguide/add-chat-to-website.html)), or a custom chat interface UI that you are building?
Custom Chat Interface UI, with [customChatWidget](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/customChatWidget).
> * Has this impacted any other chat functionality that is block this use case?
No, only this one.
> * Is this error occurring for every single chat widget rendering on your website?
Yes, only if user exit widget without response.
> * Is this preventing the user from starting a new chat even after closing/opening the widget?
No, it closes normally.
> * What POST `/participant/event` request is being sent?
![image](https://github.com/amazon-connect/amazon-connect-chat-interface/assets/111007403/3eb538dd-495e-4d94-b72f-5fec15e3c398)
![image](https://github.com/amazon-connect/amazon-connect-chat-interface/assets/111007403/60c1320a-0d10-4f01-a8c2-271a56113e5a)

I know that this type of read event cannot be sent after disconnection, because of the token, but, it happens after disconnection. It only happens 1 time after disconnecting, it is not a loop.
